lib/dashboard/config/routes.rb
Moteel::Application.routes.draw do

  namespace :service do |serve|
    resources :hotels, :as => 'entity' do
      collection do
        get 'available_rooms'
        get 'managers'
        get 'users'

      end
    end
    resources :reservations do
      collection do
        get 'create'
        get 'show'
        get 'delete'
      end
    end
    resources :checkins, :controller => 'checkin' do
      member do
        post 'check_out'
        get 'add_service_charge'
        get 'add_service_payment'
      end
    end
  end
  resources :hotel_reviews, :as => 'entity_reviews'
  resources :hotel_modules, :as => 'entity_modules'

  resources :hotel_payment_types, :as => 'entity_payment_types' do
    member do
      put 'change_status'
    end
  end

  resources :hotel_discounts, :path => 'entity_discounts' do
    collection do
      post 'delete_multiple'
    end
  end
  resources :hotel_reviews, :as => 'entity_reviews'
  resources :hotels, :as => 'entity' do
    member do
      put 'change_status'
      put 'change_featured_status'
      delete 'delete_featured'
      get 'location_map'
      get 'amenities'
      get 'rooms'
      get 'policies'
      get 'description'
      get 'photos'
      get 'videos'
      get 'inquiry'
      get 'reviews'
      get 'contact'
      get 'invalidate_cache'
      get 'custom_action'
    end
    collection do
      get 'search'
      get 'country_changed'
      post 'send_feedback'
      post 'delete_image'
      get 'redirect_provider'
      get 'api_hotel_rooms'
      post 'delete_logo'
      get 'show_api'
      get 'assign_template'
      get 'assign_theme'
      post 'assign_theme'
      get 'render_google_map'
      get 'list'
      get 'featured_requests'
      get 'make_featured'
      post 'make_featured'
      get 'featured'
      post 'do_featured'
      post 'auto_complete_for_hotel'
    end
  end

  resources :rooms, :as => 'items' do
    collection do
      get 'category_changed'
      get 'info_for_reserve'
      get 'booking_local'
      get 'amenities'
      get 'available_particular_room'
      post 'delete_image'
      post 'add_service'
      post 'delete_multiple'
      post 'switch_branch'
      post 'auto_complete_results'
    end
    member do
      put 'change_status'
    end
  end
  resources :room_types, :as => 'item_types' do
    collection do
      get 'category_changed'
      get 'detail_info'
      get 'info_for_reserve'
      post 'delete_image'
      get 'amenities'
    end
    member do
      put 'change_status'
    end
  end
  namespace :user_panel do |user_panel|
    resources :hotels, :as => 'entity', :only => [:index] do
      collection do
        post 'make_featured'
        get 'check_in'
        get 'check_out'
        get 'clicked_bill'
      end
    end
    resources :hotel_assignments, :as => 'entity_assignments', :only => [:create]
    resources :recharge_requests, :only => [:index]
    resources :room_types, :as => 'item_types', :only => [:index]
    resources :rooms, :as => 'items', :only => [:index]
    resources :finances, :only => [:index] do
      collection do
        get 'view_balance'
        get 'billing_statement'
      end
    end

    resources :feedbacks, :only => [:index] do
      collection do
        get 'featured_request'
        get 'reply_feedback'
        get 'delete_feedback'
      end
    end
  end
  #resources :users
  get 'my/entity_reports' => 'users#moteel_reports_users', :as => 'moteel_reports_users'
  get 'assign_entity' => 'users#assign_hotel_users', :as => 'assign_hotel_users'

  get 'my/entity_list' => 'users#hotel_list_users', :as => 'hotel_list_users'
  get 'my/item_type_list' => 'users#room_type_list_users', :as => 'room_type_list_users'
  get 'my/item_list' => 'users#room_list_users', :as => 'room_list_users'

  get 'entity_visit_detail/:id' => 'users#hotel_visit_detail', :as => 'hotel_visit_detail'

  get 'dashboard' => 'dashboard#home', :as => 'dashboard_home'

  get 'housekeeping' => 'housekeeping#home', :as => 'housekeeping'
  get 'housekeeping_print' => 'housekeeping#home_print', :as => 'housekeeping_print'
  post 'update_housekeeping_status' => 'housekeeping#update_housekeeping_status'
  post 'assign_employee_housekeeping' => 'housekeeping#assign_employee'
  post 'remove_employee_housekeeping' => 'housekeeping#remove_employee'

  get 'room_service' => 'room_service#home', :as => 'room_service'
  post 'assign_employee_room_service' => 'room_service#assign_employee'
  post 'update_room_service_status' => 'room_service#update_status'

  get 'reports_base' => 'reports_base#home', :as => 'reports_base'
  get 'all_branch_reports' => 'all_branch_reports#home', :as => 'all_branch_reports'
  get 'room_occupancy_report' => 'reports_base#room_occupancy_report', :as => 'room_occupancy_report'
  get 'sales_by_services_report' => 'reports_base#sales_by_services_report', :as => 'sales_by_services_report'

  get 'cashier_desk' => 'cashier_desk#home'
  #For Report
  get 'inventory_transaction_list_report' => 'housekeeping/housekeeping_reports#inventory_transaction_list', :as => 'inventory_transaction_list_report'
  post 'inventory_transaction_list_report' => 'housekeeping/housekeeping_reports#inventory_transaction_list', :as => 'inventory_transaction_list_report'
  get 'fixed_asset_transactions_report' => 'housekeeping/housekeeping_reports#fixed_asset_allocation_history', :as => 'fixed_asset_transactions_report'
  post 'email_fixed_asset_allocation_pdf' => 'housekeeping/housekeeping_reports#email_fixed_asset_allocation_pdf', :as => 'email_fixed_asset_allocation_pdf'
  get 'service_wise_revenue_report' => 'housekeeping/housekeeping_reports#service_wise_revenue', :as => 'service_wise_revenue_report'
  post 'email_service_wise_revenue_pdf' => 'housekeeping/housekeeping_reports#email_service_wise_revenue_pdf', :as => 'email_service_wise_revenue_pdf'
  get 'payment_type_wise_transactions_report' => 'housekeeping/housekeeping_reports#payment_type_wise_transactions', :as => 'payment_type_wise_transactions_report'
  post 'payment_type_wise_transactions_report' => 'housekeeping/housekeeping_reports#payment_type_wise_transactions', :as => 'payment_type_wise_transactions_report'
  get 'deposit_listing_report' => 'housekeeping/housekeeping_reports#deposit_listing', :as => 'deposit_listing_report'
  post 'email_deposit_listing_pdf' => 'housekeeping/housekeeping_reports#email_deposit_listing_pdf', :as => 'email_deposit_listing_pdf'
  get 'financial_statement_report' => 'housekeeping/housekeeping_reports#financial_statement', :as => 'financial_statement_report'
  post 'financial_statement_report' => 'housekeeping/housekeeping_reports#financial_statement', :as => 'financial_statement_report'
  get 'billing_information_report' => 'housekeeping/housekeeping_reports#billing_information', :as => 'billing_information_report'
  post 'email_billing_information_pdf' => 'housekeeping/housekeeping_reports#email_billing_information_pdf', :as => 'email_billing_information_pdf'
  get 'cashier_statement_report' => 'housekeeping/housekeeping_reports#cashier_statement', :as => 'cashier_statement_report'
  post 'email_cashier_statement_pdf' => 'housekeeping/housekeeping_reports#email_cashier_statement_pdf', :as => 'email_cashier_statement_pdf'
  get 'revenue_by_counter_report' => 'housekeeping/housekeeping_reports#revenue_by_counter', :as => 'revenue_by_counter_report'
  post 'email_revenue_by_counter_pdf' => 'housekeeping/housekeeping_reports#email_revenue_by_counter_pdf', :as => 'email_revenue_by_counter_pdf'

  #End Report
  namespace :reporting_service do |service|
    resources :items do
      member do
        post 'create'
        get 'new'
      end
    end
  end
  get 'front_desk' => 'reporting_service/items#availability_list', :as => 'front_desk'
  get 'stay_view' => 'reporting_service/items#stay_view', :as => 'stay_view'
  get 'quick_view' => 'reporting_service/items#quick_view', :as => 'quick_view'
  get 'quick_view_future_inventory' => 'reporting_service/items#quick_view_future_inventory', :as => 'quick_view_future_inventory'
  get 'quick_view_future_inventory_more' => 'reporting_service/items#quick_view_future_inventory_more', :as => 'quick_view_future_inventory_more'
  #reporting
  get 'report_checkin' => 'reporting_service/reports#report_checkin', :as => 'report_checkin'
  get 'report_available' => 'reporting_service/reports#report_available', :as => 'report_available'
  get 'report_maintenance' => 'reporting_service/reports#report_maintenance', :as => 'report_maintenance'
  get 'report_pending_checkout' => 'reporting_service/reports#report_pending_checkout', :as => 'report_pending_checkout'

end

lib/dashboard/app/views/housekeeping/housekeeping_reports/part/_billing_information_filter.html.erb
<div class="views">
  <%= form_for(:transaction_report, :url => billing_information_report_path, :method => 'get', :remote => true) do |f| %>
    <%
       @start_id = 'start_date_' + Time.now.to_i.to_s
       @end_id = 'end_date_' + Time.now.to_i.to_s
    %>
    <div class="edit_wrapper car_input_row">
      <div class="manage_input" >
        <label><%= t('views.labels.start_date') %></label>

        <div class="dt_txt">
          <%= text_field_tag "start_date", params[:start_date]? params[:start_date] : Time.zone.today.strftime('%Y-%m-%d'),
                             :class => 'datepicker',
                             :id => @start_id,
                             "data-less-than-eq-field" => @end_id
          %>
        </div>
      </div>
      <div class="manage_input" >
        <label><%= t('views.labels.end_date') %></label>

        <div class="dt_txt">
          <%= text_field_tag "end_date", params[:end_date]? params[:end_date] : Time.zone.today.strftime('%Y-%m-%d'),
                             :class => 'datepicker',
                             :id => @end_id,
                             "data-greater-than-eq-field" => @start_id
          %>
        </div>
      </div>
      <div class="manage_input" style="width: 20%">
        <label><%= t('views.labels.group_type') %></label>
        <%= select_tag :group_type, options_for_select(Constants::GROUP_TYPES), :prompt => t('views.labels.select') %>
      </div>
      <div class="manage_input" style="width: 10%">
        <%= hidden_field_tag :lan, I18n.locale %>
        <%= hidden_field_tag :target_dom_id, 'rpt_billing_information_content' %>
        <%= hidden_field_tag :content_body_selector, '#billing_information_content_body' %>

        <input name="submit" type="submit" class="go_btn centered_button " value="<%= t('views.labels.search') %>"/>
      </div>
    </div>
  <% end %>
</div>

lib/dashboard/app/views/housekeeping/housekeeping_reports/part/_cashier_statement_body.html.erb
<% if @transaction_list.present? %>
    <div style="clear: both">
      <%= render :partial => 'shared/email_report_lb', :locals => {:parameterised_url => email_cashier_statement_pdf_path(:start_date => params[:start_date], :end_date => params[:end_date], :cash_counter_id => params[:cash_counter_id], :submit => params[:submit], :report_type => 'email'), :email_body_id => 'email_cashier_statement_id'} %>
      <div class="gp_stay_links gap-right">
        <%= link_to t('views.labels.email'), 'javascript:void(0)', :onclick => "showEmailModalbox('email_cashier_statement_id')"  %>
        <%= link_to_csv %>
        <%= link_to_pdf %>
      </div>
      <div class="report_container">
        <%= render :partial => "shared/table", :locals => {:items => @transaction_list,
                                                           :total_col_span => 2,
                                                           :sum_column_titles => [t('views.labels.amount')]} %>
      </div>
    </div>

<% end %>

lib/dashboard/app/views/housekeeping/housekeeping_reports/part/_cashier_statement_content.html.erb
<div class=" clear groups_stay_form">
<%= render :partial => 'housekeeping/housekeeping_reports/part/cashier_statement_filter' %>
</div>
<div class="room_listing_desc" id="cashier_statement_content_body">

<%= render :partial => 'housekeeping/housekeeping_reports/part/cashier_statement_body' %>
  </div>

lib/dashboard/app/views/housekeeping/housekeeping_reports/part/_cashier_statement_filter.html.erb
<div class="views">
  <%= form_for(:transaction_report, :url => cashier_statement_report_path, :method => 'get',:remote => true) do |f| %>
    <%
       @start_id = 'start_date_' + Time.now.to_i.to_s
       @end_id = 'end_date_' + Time.now.to_i.to_s
    %>
    <div class="edit_wrapper car_input_row">
      <div class="manage_input">
        <label><%= t('views.labels.start_date') %></label>

        <div class="dt_txt">
          <%= text_field_tag "start_date", params[:start_date]? params[:start_date] : Time.zone.today.strftime('%Y-%m-%d'),
                             :class => 'datepicker',
                             :id => @start_id,
                             "data-less-than-eq-field" => @end_id
          %>
        </div>
      </div>
      <div class="manage_input">
        <label><%= t('views.labels.end_date') %></label>

        <div class="dt_txt">
          <%= text_field_tag "end_date", params[:end_date]? params[:end_date] : Time.zone.today.strftime('%Y-%m-%d'),
                             :class => 'datepicker',
                             :id => @end_id,
                             "data-greater-than-eq-field" => @start_id
          %>
        </div>
      </div>
      <div class="manage_input" style="width: 25%">
        <label><%= t('views.labels.select_counter') %></label>
        <%= select_tag 'cash_counter_id', options_from_collection_for_select(@cash_counters, "id", "name", params[:cash_counter_id]), {:prompt => t('views.labels.all_counter')} %>
      </div>

      <div class="">
        <%= hidden_field_tag :lan, I18n.locale %>
        <%=hidden_field_tag :target_dom_id, 'rpt_cashier_statement_content'%>
        <%=hidden_field_tag :content_body_selector, '#cashier_statement_content_body'%>

        <input name="submit" type="submit" class="go_btn centered_button " value="<%= t('views.labels.search') %>"/>
      </div>
    </div>
  <% end %>
</div>

lib/dashboard/app/views/housekeeping/housekeeping_reports/part/_deposit_listing_body.html.erb
<% if @transaction_list.present? %>

    <div style="clear: both">
      <%= render :partial => 'shared/email_report_lb', :locals => {:parameterised_url => email_deposit_listing_pdf_path(:start_date => params[:start_date], :end_date => params[:end_date], :checkstatus => params[:checkstatus], :submit => params[:submit], :report_type => 'email'), :email_body_id => 'email_deposit_listing_id'} %>
      <div class="gp_stay_links gap-right">
        <%= link_to t('views.labels.email'), 'javascript:void(0)', :onclick => "showEmailModalbox('email_deposit_listing_id')"  %>
        <%= link_to_csv %>
        <%= link_to_pdf %>
      </div>
      <div class="report_container">
        <%= render :partial => "shared/table", :locals => {:items => @transaction_list,
                                                           :total_col_span => 1,
                                                           :sum_column_titles => [t('views.labels.deposit_amount')]} %>
      </div>
    </div>
<% end %>

lib/dashboard/app/views/housekeeping/housekeeping_reports/part/_deposit_listing_filter.html.erb
<div class="views">
  <%= form_for(:transaction_report, :url => deposit_listing_report_path, :method => 'get', :remote => true) do |f| %>
    <%
       @start_id = 'start_date_' + Time.now.to_i.to_s
       @end_id = 'end_date_' + Time.now.to_i.to_s
    %>
    <div class="edit_wrapper car_input_row">
      <div class="manage_input">
        <label><%= t('views.labels.start_date') %></label>
        <div class="dt_txt">
          <%= text_field_tag "start_date", params[:start_date]? params[:start_date] : Time.zone.today.strftime('%Y-%m-%d'),
                             :class => 'datepicker',
                             :id => @start_id,
                             "data-less-than-eq-field" => @end_id
          %>
        </div>
      </div>
      <div class="manage_input">
        <label><%= t('views.labels.end_date') %></label>
        <div class="dt_txt">
          <%= text_field_tag "end_date", params[:end_date]? params[:end_date] : Time.zone.today.strftime('%Y-%m-%d'),
                             :class => 'datepicker',
                             :id => @end_id,
                             "data-greater-than-eq-field" => @start_id
          %>
        </div>
      </div>

      <div class="manage_input dp_list mtop8" style="width: 30%">

        <%= radio_button_tag 'checkstatus', Constants::CHECK_IN_STATUSES[:checked_in] %>
        <label for="theme"><%= t('views.labels.check_in') %></label>

        <%= radio_button_tag 'checkstatus', Constants::CHECK_IN_STATUSES[:checked_out] %>
        <label for="theme"><%= t('views.labels.check_out') %></label>

        <%= radio_button_tag 'checkstatus', 'DepositDate' %>
        <label for="theme"><%= t('views.labels.deposit_date') %></label>
      </div>

      <div class="">
        <%=hidden_field_tag :lan, I18n.locale%>
        <%=hidden_field_tag :target_dom_id, 'rpt_deposit_listing_content'%>
        <%=hidden_field_tag :content_body_selector, '#deposit_listing_content_body'%>

        <input name="submit" type="submit" class="go_btn centered_button " value="<%= t('views.labels.search') %>"/>
      </div>
    </div>
  <% end %>

</div>

lib/dashboard/app/views/housekeeping/housekeeping_reports/part/_financial_statement_content.html.erb
<div class="clear groups_stay_form">
<%= render :partial => 'housekeeping/housekeeping_reports/part/financial_statement_filter' %>
  </div>
<div class="room_listing_desc" id="financial_statement_content_body">
<%= render :partial => 'housekeeping/housekeeping_reports/part/financial_statement_body' %>
  </div>

lib/dashboard/app/views/housekeeping/housekeeping_reports/part/_financial_statement_filter.html.erb
<div class="views">
  <%= form_for(:transaction_report, :url => financial_statement_report_path, :method => 'get',:remote => true) do |f| %>
    <%
       @start_id = 'start_date_' + Time.now.to_i.to_s
       @end_id = 'end_date_' + Time.now.to_i.to_s
    %>
    <div class="edit_wrapper car_input_row">
      <div class="manage_input"  >
        <label><%= t('views.labels.start_date') %></label>
        <div class="dt_txt">
          <%= text_field_tag "start_date", params[:start_date]? params[:start_date] : Time.zone.today.strftime('%Y-%m-%d'),
                             :class => 'datepicker',
                             :id => @start_id,
                             "data-less-than-eq-field" => @end_id
          %>
        </div>
      </div>
      <div class="manage_input"  >
        <label><%= t('views.labels.end_date') %></label>
        <div class="dt_txt">
          <%= text_field_tag "end_date", params[:end_date]? params[:end_date] : Time.zone.today.strftime('%Y-%m-%d'),
                             :class => 'datepicker',
                             :id =>@end_id,
                             "data-greater-than-eq-field" => @start_id
          %>
        </div>

      </div>

      <div class="manage_input"  style="width: 21%">
        <label><%= t('views.labels.or') %></label>
        <div class="dt_txt" style="border: none; background: none; width: 80%">

          <%= select_tag('days_count', options_for_select(translate_days_count_options(Constants::DAYS_COUNT_OPTIONS_FINANCIAL_STATEMENT), params[:days_count].to_i), :class => 'filter-duration', :style=>'width:90%', :prompt => t('views.labels.select_duration')) %>
        </div>
      </div>

      <div class="manage_input" style="width: 10%">
        <%=hidden_field_tag :lan, I18n.locale%>
        <%=hidden_field_tag :target_dom_id, 'rpt_financial_statement_content'%>
        <%=hidden_field_tag :content_body_selector, '#financial_statement_content_body'%>
        <input name="submit" type="submit" class="go_btn centered_button " value="<%= t('views.labels.search') %>"/>
      </div>
    </div>
  <% end %>

</div>

<script type="text/javascript">
  $j(document).ready(function() {

    /* duration dropdown changed */
    $j('#days_count').live('change', function() {

      var sel_value = $j('#days_count').val();
      if (sel_value == '1')
      {
        $j('#<%= @end_id %>').datepicker('setDate', '<%= Time.zone.today %>');
        $j('#<%= @start_id %>').datepicker('setDate', '<%= Time.zone.today.at_beginning_of_week %>');
        $j('#<%= @start_id %>').datepicker({ dateFormat: 'yy-mm-dd' })
      }
      else if (sel_value == '2')
      {
        $j('#<%= @end_id %>').datepicker('setDate', '<%= Time.zone.today %>');
        $j('#<%= @start_id %>').datepicker('setDate', '<%= Time.zone.today.at_beginning_of_month %>');
        $j('#<%= @start_id %>').datepicker({ dateFormat: 'yy-mm-dd' })
      }
      else if (sel_value == '3')
      {
        $j('#<%= @end_id %>').datepicker('setDate', '<%= Time.zone.today %>');
        $j('#<%= @start_id %>').datepicker('setDate', '<%= Time.zone.today.at_beginning_of_year %>');
        $j('#<%= @start_id %>').datepicker({ dateFormat: 'yy-mm-dd' })
      }


    });

  });
</script>

lib/dashboard/app/views/housekeeping/housekeeping_reports/part/_revenue_by_counter_body.html.erb
<% if @transaction_list.present? %>
    <div style="clear: both">
      <%=render :partial => 'shared/email_report_lb', :locals => {:parameterised_url => email_revenue_by_counter_pdf_path(:start_date => params[:start_date], :end_date => params[:end_date], :cash_counter_id => params[:cash_counter_id], :submit => params[:submit], :report_type => 'email'),:email_body_id => 'email_revenue_counter_id'}%>
      <div class="gp_stay_links gap-right">
      <%= link_to t('views.labels.email'), 'javascript:void(0)', :onclick => "showEmailModalbox('email_revenue_counter_id')" %>
      <%= link_to_csv %>
      <%= link_to_pdf %>
    </div>
    <div class="report_container">
    <%= render :partial => "shared/table", :locals => {:items => @transaction_list,
                                                       :total_col_span => 2,
                                                       :sum_column_titles => [t('views.labels.amount')]} %>
  </div>
  </div>

<% end %>

lib/dashboard/app/views/housekeeping/housekeeping_reports/part/_revenue_by_counter_content.html.erb
<div class=" clear groups_stay_form">
<%= render :partial => 'housekeeping/housekeeping_reports/part/revenue_by_counter_filter' %>
  </div>
<div class="room_listing_desc" id="revenue_by_counter_content_body">
<%= render :partial => 'housekeeping/housekeeping_reports/part/revenue_by_counter_body' %>
  </div>

lib/dashboard/app/views/housekeeping/housekeeping_reports/part/_revenue_by_counter_filter.html.erb
<div class="views">
  <%= form_for(:transaction_report, :url => revenue_by_counter_report_path, :method => 'get', :remote => true) do |f| %>
    <%
       @start_id = 'start_date_' + Time.now.to_i.to_s
       @end_id = 'end_date_' + Time.now.to_i.to_s
    %>
    <div class="edit_wrapper car_input_row">
      <div class="manage_input">
        <label><%= t('views.labels.start_date') %></label>
        <div class="dt_txt">
          <%= text_field_tag "start_date", params[:start_date]? params[:start_date] : Time.zone.today.strftime('%Y-%m-%d'),
                             :class => 'datepicker',
                             :id =>@start_id,
                             "data-less-than-eq-field" => @end_id %>
        </div>
      </div>
      <div class="manage_input">
        <label><%= t('views.labels.end_date') %></label>
        <div class="dt_txt">
          <%= text_field_tag "end_date", params[:end_date]? params[:end_date] : Time.zone.today.strftime('%Y-%m-%d'),
                             :class => 'datepicker',
                             :id => @end_id,
                             "data-greater-than-eq-field" => @start_id
          %>
        </div>
      </div>
      <div class="manage_input" style="width: 25%;">
        <label><%= t('views.labels.cash_counters') %></label>
        <%= select_tag 'cash_counter_id', options_from_collection_for_select(@cash_counters, "id", "name", params[:cash_counter_id]), {:prompt => t('views.labels.select')}%>
      </div>
      <div class="">
        <%=hidden_field_tag :lan, I18n.locale%>
        <%=hidden_field_tag :target_dom_id, 'rpt_revenue_by_counter_content'%>
        <%=hidden_field_tag :content_body_selector, '#revenue_by_counter_content_body'%>

        <input name="submit" type="submit" class="go_btn centered_button " value="<%= t('views.labels.search') %>"/>
      </div>
    </div>
  <% end %>
</div>

lib/dashboard/app/views/housekeeping/housekeeping_reports/part/_service_wise_transaction_body.html.erb
<% if @transaction_list.present? %>
    <div style="clear: both">
      <%= render :partial => 'shared/email_report_lb', :locals => {:parameterised_url => email_service_wise_revenue_pdf_path(:start_date => params[:start_date], :end_date => params[:end_date], :report_type => 'email'), :email_body_id => 'email_service_wise_id'} %>

      <div class="gp_stay_links gap-right">
        <%= link_to t('views.labels.email'), 'javascript:void(0)', :onclick => "showEmailModalbox('email_service_wise_id')" %>
        <%= link_to_csv %>
        <%= link_to_pdf %>
      </div>
      <div class="report_container">
        <%= render :partial => "shared/table", :locals => {:items => @transaction_list,
                                                           :total_col_span => 1,
                                                           :sum_column_titles => [:total_amount => t('views.labels.amount')]
        } %>
      </div>
      <%
         progress_percent = ((@total_amount * 100)/@service_revenue).to_f
      %>
      <div style=" float:left; width:98%;margin-left: 1%; margin-bottom: 1%; border: 1px solid #D5D5D5">
        <div style="float: left; padding-left: 5px; padding-top: 5px; width: 40%; ">
          <strong><%= t('views.labels.total') %> :<%= @service_revenue %></strong></div>
        <div style="float: left; width: 55%; padding-left: 10px; padding-top: 5px;border-left: 1px solid #D5D5D5" class=" twitter-bootstrap-root">
          <div style="float: left; width:40%"><%= t('views.labels.service_wise_revenue_ratio') %></div>
          <div class="progress " style="float: left; width:50%">
            <div class="bar" style="width:<%= progress_percent.round(2) %>%; padding-top: 2px;"><%= progress_percent.round(2) %>
              %
            </div>
          </div>

        </div>
      </div>


    </div>

<% end %>

lib/dashboard/app/views/housekeeping/housekeeping_reports/part/_service_wise_transaction_content.html.erb
<div class=" clear groups_stay_form">
<%= render :partial => 'housekeeping/housekeeping_reports/part/service_wise_transaction_filter' %>
</div>
<div class="room_listing_desc" id="service_wise_transaction_content_body">

<%= render :partial => 'housekeeping/housekeeping_reports/part/service_wise_transaction_body' %>
</div>

lib/dashboard/app/views/housekeeping/housekeeping_reports/part/_service_wise_transaction_filter.html.erb
<div class="views">
  <%= form_for(:transaction_report, :url => service_wise_revenue_report_path, :method => 'get', :remote => true) do |f| %>
    <%
       @start_id = 'start_date_' + Time.now.to_i.to_s
       @end_id = 'end_date_' + Time.now.to_i.to_s
    %>

    <div class="edit_wrapper car_input_row">
      <div class="manage_input" >
        <label><%= t('views.labels.start_date') %></label>
        <div class="dt_txt">
          <%= text_field_tag "start_date", params[:start_date]? params[:start_date] : Time.zone.today.strftime('%Y-%m-%d'),
                             :class => 'datepicker',
                             :id =>@start_id,
                             "data-less-than-eq-field" => @end_id
          %>
        </div>
      </div>
      <div class="manage_input" >
        <label><%= t('views.labels.end_date') %></label>
        <div class="dt_txt">
          <%= text_field_tag "end_date", params[:end_date]? params[:end_date] : Time.zone.today.strftime('%Y-%m-%d'),
                             :class => 'datepicker',
                             :id => @end_id,
                             "data-greater-than-eq-field" => @start_id
          %>
        </div>
      </div>
      <div class="manage_input"  style="width: 20%">
        <label><%= t('views.labels.services') %></label>
        <%= select_tag 'service_id', options_from_collection_for_select(@services, "id", "name", params[:service_id]), {:prompt => t('views.labels.all_service')}%>
      </div>
      <div class="manage_input"  style="width: 20%">
        <%=hidden_field_tag :lan, I18n.locale%>
        <%=hidden_field_tag :target_dom_id, 'rpt_service_wise_revenue_content'%>
        <%=hidden_field_tag :content_body_selector, '#service_wise_transaction_content_body'%>
        <input name="submit" type="submit" class="go_btn centered_button " value="<%= t('views.labels.search') %>"/>
      </div>
    </div>
  <% end %>
</div>