lib/dashboard/config/routes.rb
Moteel::Application.routes.draw do

  namespace :service do |serve|
    resources :hotels, :as => 'entity' do
      collection do
        get 'available_rooms'
        get 'managers'
        get 'users'

      end
    end
    resources :reservations do
      collection do
        get 'create'
        get 'show'
        get 'delete'
      end
    end
    resources :checkins, :controller => 'checkin' do
      member do
        post 'check_out'
        get 'add_service_charge'
        get 'add_service_payment'
      end
    end
  end
  resources :hotel_reviews, :as => 'entity_reviews'
  resources :hotel_modules, :as => 'entity_modules'

  resources :hotel_payment_types, :as => 'entity_payment_types' do
    member do
      put 'change_status'
    end
  end

  resources :hotel_discounts, :path => 'entity_discounts' do
    collection do
      post 'delete_multiple'
    end
  end
  resources :hotel_reviews, :as => 'entity_reviews'
  resources :hotels, :as => 'entity' do
    member do
      put 'change_status'
      put 'change_featured_status'
      delete 'delete_featured'
      get 'location_map'
      get 'amenities'
      get 'rooms'
      get 'policies'
      get 'description'
      get 'photos'
      get 'videos'
      get 'inquiry'
      get 'reviews'
      get 'contact'
      get 'invalidate_cache'
      get 'custom_action'
    end
    collection do
      get 'search'
      get 'country_changed'
      post 'send_feedback'
      post 'delete_image'
      get 'redirect_provider'
      get 'api_hotel_rooms'
      post 'delete_logo'
      get 'show_api'
      get 'assign_template'
      get 'assign_theme'
      post 'assign_theme'
      get 'render_google_map'
      get 'list'
      get 'featured_requests'
      get 'make_featured'
      post 'make_featured'
      get 'featured'
      post 'do_featured'
      post 'auto_complete_for_hotel'
    end
  end

  resources :rooms, :as => 'items' do
    collection do
      get 'category_changed'
      get 'info_for_reserve'
      get 'booking_local'
      get 'amenities'
      get 'available_particular_room'
      post 'delete_image'
      post 'add_service'
      post 'delete_multiple'
      post 'switch_branch'
      post 'auto_complete_results'
    end
    member do
      put 'change_status'
    end
  end
  resources :room_types, :as => 'item_types' do
    collection do
      get 'category_changed'
      get 'detail_info'
      get 'info_for_reserve'
      post 'delete_image'
      get 'amenities'
    end
    member do
      put 'change_status'
    end
  end
  namespace :user_panel do |user_panel|
    resources :hotels, :as => 'entity', :only => [:index] do
      collection do
        post 'make_featured'
        get 'check_in'
        get 'check_out'
        get 'clicked_bill'
      end
    end
    resources :hotel_assignments, :as => 'entity_assignments', :only => [:create]
    resources :recharge_requests, :only => [:index]
    resources :room_types, :as => 'item_types', :only => [:index]
    resources :rooms, :as => 'items', :only => [:index]
    resources :finances, :only => [:index] do
      collection do
        get 'view_balance'
        get 'billing_statement'
      end
    end

    resources :feedbacks, :only => [:index] do
      collection do
        get 'featured_request'
        get 'reply_feedback'
        get 'delete_feedback'
      end
    end
  end
  #resources :users
  get 'my/entity_reports' => 'users#moteel_reports_users', :as => 'moteel_reports_users'
  get 'assign_entity' => 'users#assign_hotel_users', :as => 'assign_hotel_users'

  get 'my/entity_list' => 'users#hotel_list_users', :as => 'hotel_list_users'
  get 'my/item_type_list' => 'users#room_type_list_users', :as => 'room_type_list_users'
  get 'my/item_list' => 'users#room_list_users', :as => 'room_list_users'

  get 'entity_visit_detail/:id' => 'users#hotel_visit_detail', :as => 'hotel_visit_detail'

  get 'dashboard' => 'dashboard#home', :as => 'dashboard_home'

  get 'housekeeping' => 'housekeeping#home', :as => 'housekeeping'
  get 'housekeeping_print' => 'housekeeping#home_print', :as => 'housekeeping_print'
  post 'update_housekeeping_status' => 'housekeeping#update_housekeeping_status'
  post 'assign_employee_housekeeping' => 'housekeeping#assign_employee'
  post 'remove_employee_housekeeping' => 'housekeeping#remove_employee'

  get 'room_service' => 'room_service#home', :as => 'room_service'
  post 'assign_employee_room_service' => 'room_service#assign_employee'
  post 'update_room_service_status' => 'room_service#update_status'

  get 'reports_base' => 'reports_base#home', :as => 'reports_base'
  get 'all_branch_reports' => 'all_branch_reports#home', :as => 'all_branch_reports'
  get 'room_occupancy_report' => 'reports_base#room_occupancy_report', :as => 'room_occupancy_report'
  get 'sales_by_services_report' => 'reports_base#sales_by_services_report', :as => 'sales_by_services_report'

  get 'cashier_desk' => 'cashier_desk#home'
  #For Report
  get 'inventory_transaction_list_report' => 'housekeeping/housekeeping_reports#inventory_transaction_list', :as => 'inventory_transaction_list_report'
  post 'inventory_transaction_list_report' => 'housekeeping/housekeeping_reports#inventory_transaction_list', :as => 'inventory_transaction_list_report'
  get 'fixed_asset_transactions_report' => 'housekeeping/housekeeping_reports#fixed_asset_allocation_history', :as => 'fixed_asset_transactions_report'
  post 'email_fixed_asset_allocation_pdf' => 'housekeeping/housekeeping_reports#email_fixed_asset_allocation_pdf', :as => 'email_fixed_asset_allocation_pdf'
  get 'service_wise_revenue_report' => 'housekeeping/housekeeping_reports#service_wise_revenue', :as => 'service_wise_revenue_report'
  post 'email_service_wise_revenue_pdf' => 'housekeeping/housekeeping_reports#email_service_wise_revenue_pdf', :as => 'email_service_wise_revenue_pdf'
  get 'payment_type_wise_transactions_report' => 'housekeeping/housekeeping_reports#payment_type_wise_transactions', :as => 'payment_type_wise_transactions_report'
  post 'payment_type_wise_transactions_report' => 'housekeeping/housekeeping_reports#payment_type_wise_transactions', :as => 'payment_type_wise_transactions_report'
  get 'deposit_listing_report' => 'housekeeping/housekeeping_reports#deposit_listing', :as => 'deposit_listing_report'
  post 'email_deposit_listing_pdf' => 'housekeeping/housekeeping_reports#email_deposit_listing_pdf', :as => 'email_deposit_listing_pdf'
  get 'financial_statement_report' => 'housekeeping/housekeeping_reports#financial_statement', :as => 'financial_statement_report'
  post 'financial_statement_report' => 'housekeeping/housekeeping_reports#financial_statement', :as => 'financial_statement_report'
  get 'billing_information_report' => 'housekeeping/housekeeping_reports#billing_information', :as => 'billing_information_report'
  post 'email_billing_information_pdf' => 'housekeeping/housekeeping_reports#email_billing_information_pdf', :as => 'email_billing_information_pdf'
  get 'cashier_statement_report' => 'housekeeping/housekeeping_reports#cashier_statement', :as => 'cashier_statement_report'
  post 'email_cashier_statement_pdf' => 'housekeeping/housekeeping_reports#email_cashier_statement_pdf', :as => 'email_cashier_statement_pdf'
  get 'revenue_by_counter_report' => 'housekeeping/housekeeping_reports#revenue_by_counter', :as => 'revenue_by_counter_report'
  post 'email_revenue_by_counter_pdf' => 'housekeeping/housekeeping_reports#email_revenue_by_counter_pdf', :as => 'email_revenue_by_counter_pdf'

  #End Report
  namespace :reporting_service do |service|
    resources :items do
      member do
        post 'create'
        get 'new'
      end
    end
  end
  get 'front_desk' => 'reporting_service/items#availability_list', :as => 'front_desk'
  get 'stay_view' => 'reporting_service/items#stay_view', :as => 'stay_view'
  get 'quick_view' => 'reporting_service/items#quick_view', :as => 'quick_view'
  get 'quick_view_future_inventory' => 'reporting_service/items#quick_view_future_inventory', :as => 'quick_view_future_inventory'
  get 'quick_view_future_inventory_more' => 'reporting_service/items#quick_view_future_inventory_more', :as => 'quick_view_future_inventory_more'
  #reporting
  get 'report_checkin' => 'reporting_service/reports#report_checkin', :as => 'report_checkin'
  get 'report_available' => 'reporting_service/reports#report_available', :as => 'report_available'
  get 'report_maintenance' => 'reporting_service/reports#report_maintenance', :as => 'report_maintenance'
  get 'report_pending_checkout' => 'reporting_service/reports#report_pending_checkout', :as => 'report_pending_checkout'

end

lib/dashboard/app/controllers/housekeeping_controller.rb
class HousekeepingController < DashboardController
  before_filter :ensure_current_branch_exists
  layout 'housekeeping'

  def home
    load_home_data
    respond_to do |format|
      format.js
      format.html
    end
  end

  def home_print
    load_home_data
    respond_to do |format|
      format.html { render :layout => 'blank' }
    end

  end

  def update_housekeeping_status
    status = params[:housekeeping_status].present? && Constants::HOUSEKEEPING_STATUS_CODES.has_key?(params[:housekeeping_status].downcase.to_sym) ? params[:housekeeping_status] : ""
    @rooms = Room.where(id: params[:set_status_selected_ids].split(','), hotel_id: current_reporting_branch_id)

    if status.present? && params[:set_status_selected_ids].present?
      @rooms.update_all(house_keeping_status: Constants::HOUSEKEEPING_STATUS_CODES[status.downcase.to_sym])
      ReportItem.in(reference_id: @rooms.pluck(:id)).update_all(house_keeping_status: Constants::HOUSEKEEPING_STATUS_CODES[status.to_sym])
      flash.now[:notice] = t('notifications.room_status_updated')
    else
      flash.now[:error] = t('notifications.room_status_update_failed')
    end

    respond_to do |format|
      format.js
    end
  end

  def assign_employee
    @rooms = Room.where(id: params[:assign_employee_selected_ids].split(','), hotel_id: current_reporting_branch_id)
    assigned_employee = User.find(params[:assigned_employee_id]) rescue nil
    housekeeping_dept = current_branch.house_keeping_department
    if assigned_employee.present? && assigned_employee.departments.include?(housekeeping_dept)
      begin
        @rooms.each { |r| r.assign_housekeeping_employee(assigned_employee, current_user, params[:task_title]) }
        flash.now[:notice] = t('notifications.operation_successful')
      rescue
        flash.now[:error] = t('notifications.operation_failed')
      end

    else
      flash.now[:error] = t('notifications.operation_failed')
    end

    respond_to do |format|
      format.js
    end
  end

  def remove_employee
    task = Task.find(params[:task_id])
    if task.destroy
      flash.now[:notice] = t('notifications.operation_successful')
    else
      flash.now[:error] = t('notifications.operation_failed')
    end
    respond_to do |format|
      format.js
    end
  end

  private

  def load_home_data
    @selected_menu = 'house_keeping'
    @selected_room_type = ""

    if params[:room_type_id].present?
      @rooms = Room.where(room_type_id: params[:room_type_id].to_i, hotel_id: current_reporting_branch_id).includes(:room_type => :translations)
      @selected_room_type = params[:room_type_id]
    else
      @rooms = Room.where(hotel_id: current_reporting_branch_id).includes(:room_type => :translations)
    end

    @room_types = RoomType.where(hotel_id: current_reporting_branch_id).includes(:translations)
    status_data
    @assigned_users = current_branch.house_keeping_department.users.includes(:profile => :translations)
    entity_daily_activity = ReportEntityDailyActivity.where(date: Time.zone.today, entity_id: current_reporting_branch_id).first rescue {}
    @todays_activity_count = entity_daily_activity[:todays_activity_count] rescue {}
    @todays_statistics = entity_daily_activity[:todays_statistics] rescue {}
  end

  def status_data
    @status_data = {}
    room_ids = @rooms.pluck(:id)
    ReportItemDailyActivity.where(date: Time.now.to_date, second_shift: true).in(item_id: room_ids).only(["status", "item_id"]).each do |row|
      @status_data[row.item_id] = row.status
    end

    @remarks_and_assignments = {}
    Task.with_room(room_ids).due_between.incomplete.includes(:assigned_user).each do |task|
      @remarks_and_assignments[task.room_id] ||= {}
      @remarks_and_assignments[task.room_id][:assigned_user_task] ||= []
      @remarks_and_assignments[task.room_id][:assigned_user_task] << task if task.assigned_user.present?
      @remarks_and_assignments[task.room_id][:remarks] = task.title
    end
  end
end

lib/dashboard/app/views/housekeeping/_actions_with_filter.html.erb
<div class="reserv_search_row">

  <label>
    <%= t('views.labels.filter_by') %>
  </label>

  <span><%= select_tag 'filter_room_type', options_from_collection_for_select(room_types, 'id', 'title', selected_room_type.to_i), :prompt => t('views.labels.select_room_type') %></span>
  <span id="room_type_loading" style="display:none"> <%= image_tag 'spin.gif', :height => '20px', :align => 'top' %></span>

  <!--<div class="multiple_status_assign">-->
  <label><%= t('views.labels.set_housekeeping_status') %></label>

  <%= form_tag(update_housekeeping_status_path, :id => 'set_statuses_form', :name => 'set_statuses_form', :remote => true) do %>
      <%= select_tag 'housekeeping_status', options_for_select(Constants::HOUSEKEEPING_STATUS_OPTIONS.collect { |s| [t("views.labels.#{s}"), Constants::HOUSEKEEPING_STATUS_CODES[s.to_sym]] }), :prompt => t('views.labels.select') %>
      <%= hidden_field_tag 'set_status_selected_ids', '' %>
      <%= submit_tag t('views.labels.update'), :id => 'set_statuses_submit', :class => 'submit_btn' %>
  <% end %>

  <!--</div>-->

  <!--<div class="multiple_employee_assign">-->
  <label>
    <%= t('views.labels.select_employee') %>
  </label>
  <%= form_tag(assign_employee_housekeeping_path, :id => 'assign_employee_form', :name => 'assign_employee_form', :remote => true, :method => :post) do %>
      <%= select_tag 'assigned_employee_id', options_from_collection_for_select(assigned_users, 'id', 'full_name'), :prompt => t('views.labels.select'), :style => "width:65%;" %>
      <%= hidden_field_tag 'assign_employee_selected_ids', '' %>
      <%= hidden_field_tag 'task_title', '' %>
      <%= submit_tag t('views.labels.assign'), :id => 'assign_employee_submit', :'modal-title' => t('views.labels.assign_employee'), :class => 'submit_btn' %>
  <% end %>
  <!--</div>-->
</div>

lib/dashboard/app/views/housekeeping/_home_content.html.erb
<div class="border_inner_box">
  <%= render :partial => 'housekeeping/actions_with_filter', :locals => {:assigned_users => assigned_users, :room_types => room_types, :selected_room_type => selected_room_type} %>
</div>
<div class="border_inner_box">
  <table class="hk_whole_info tabular_fullwidth mid_val no_flt" cellpadding="0" cellspacing="0">
    <tr class="hk_whole_desc heading_txt no_h_bor no_flt">
      <th>
        <input type="checkbox" class="check_all" data-checkbox-css="room_select_checkbox">
      </th>
      <th>
        <%= t('views.labels.room') %>
      </th>
      <th>
        <%= t('views.labels.room_type') %>
      </th>
      <th>
        <%= t('views.labels.housekeeping_status') %>
      </th>
      <th>
        <%= t('views.labels.front_desk_status') %>
      </th>
      <th>
        <%= t('views.labels.remarks') %>
      </th>
      <th>
        <%= t('views.labels.employee') + ' ' + t('views.labels.names') %>
      </th>
    </tr>

    <%= render :partial => 'housekeeping/housekeeping_row', :locals => {:rooms => rooms, :status_data => status_data} %>

    <tfoot>
    <tr>
      <td class="no_bor" colspan="7">
        <div class="clear"></div>
        <div class="center " style="margin: 10px 0">

          <%= link_to t('views.labels.print'), housekeeping_print_path(:action_type => 'print'), :class => 'go_btn centered_button', :target => '_blank', :class => "go_btn centered_button" %>


        </div>
      </td>
    </tfoot>
    </tr>
  </table>

</div>

<script type="text/javascript">
    $j(document).ready(function () {
        $j('.check_all').live('change', function () {
            var css_class = $j(this).data('checkbox-css');
            $j('.' + css_class).attr('checked', $j(this).is(':checked'));
        });

        $j('#set_statuses_submit').live('click', function (e) {
            var roomIds = [];
            $j('.room_select_checkbox:checked').each(function () {
                roomIds.push($j(this).val());
            });
            $j('#set_status_selected_ids').val(roomIds.toString());

            $j('#set_statuses_form').submit();
            e.preventDefault();
        });

        <% Constants::HOUSEKEEPING_STATUS_CODES.each do |k, v| %>
        $j('#<%= k %>_count').text($j('.<%= k %>').size());
        <% end %>

        $j('#assign_employee_submit').live('click', function (e) {
            $j('#multiple_assign_title').val('');
            $j('#multiple_assign_task_lb').dialog({
                width: 700,
                modal: true,
                title: $j('#assign_employee_submit').attr('modal-title')
            });
            $j('#multiple_assign_task_lb #multiple_assign_title_save').removeAttr('clicked');

            e.preventDefault();
        });

        $j('#multiple_assign_title_save').live('click', function () {
            if (!$j(this).attr('clicked')) {
                $j(this).attr('clicked', true)
            }
            else {
                return false;
            }
            var roomIds = [];
            $j('.room_select_checkbox:checked').each(function () {
                roomIds.push($j(this).val());
            });
            $j('#assign_employee_selected_ids').val(roomIds.toString());
            $j('#task_title').val($j('#multiple_assign_title').val());
            $j('#assign_employee_form').submit();
            $j('#multiple_assign_task_lb').dialog('close');
        });

        $j('#filter_room_type').live('change', function (e) {
            var selectedRoomTypeId = $j('#filter_room_type').val();

            $j('#room_type_loading').show();
            $j.ajax({
                type: "GET",
                url: "/housekeeping",
                data: { room_type_id: selectedRoomTypeId }
            }).done(function () {
                        $j('#room_type_loading').hide();
                    });

            e.preventDefault();
        });

        $j('.housekeeping_status_filter a').live('click', function (e) {
            var clickedStatus = $j(this).attr("data_seed");
            $j('.housekeeping_room_row').show();
            $j('.housekeeping_room_row:not([data-status="' + clickedStatus + '"])').hide();
            e.preventDefault();
        });

        $j('.room_housekeeping_status').live('click', function (e) {

            var oldValue = $j(this).text().trim().toLowerCase().replace(" ", "_");
            var did = $j(this).data('id');
            var markup = '<select data-id="' + did + '" class="housekeeping_status" name="housekeeping_status"><option value=""><%= t("views.labels.select") %></option><option value="dirty"> <%= t("views.labels.dirty") %></option><option value="touch_up"><%= t("views.labels.touch_up") %></option><option value="clean"><%= t("views.labels.clean") %></option><option value="repair"><%= t("views.labels.repair") %></option><option value="inspect"><%= t("views.labels.inspect") %></option></select><input class="submit_btn" id="set_individual_status_submit" name="commit" type="button" value="<%= t("views.labels.go") %>"/>';
            $j(this).html(markup);
            $j(this).find('select.housekeeping_status [value="' + oldValue + '"]').attr('selected', true);
        });
        $j('.room_housekeeping_status select.housekeeping_status').live('click', function (e) {
            e.stopPropagation();
        });


        $j('#set_individual_status_submit').live('click', function (e) {
            $j('#housekeeping_status').val($j(this).prev().val());
            var data = {
                "authenticity_token": $j('#set_statuses_form input[name="authenticity_token"]').val(),
                "housekeeping_status": $j(this).prev().val(),
                "set_status_selected_ids": $j(this).prev().data('id')
            };
            $j.post("/update_housekeeping_status?lan=<%= params[:lan] %>", data);
        });

        $j('#dirty_count').text(<%= rooms.collect {|r| r.house_keeping_status}.count {|i|i=='DIRTY'} %>);
        $j('#touch_up_count').text(<%= rooms.collect {|r| r.house_keeping_status}.count {|i|i=='TOUCH_UP'} %>);
        $j('#clean_count').text(<%= rooms.collect {|r| r.house_keeping_status}.count {|i|i=='CLEAN'} %>);
        $j('#repair_count').text(<%= rooms.collect {|r| r.house_keeping_status}.count {|i|i=='REPAIR'} %>);
        $j('#inspect_count').text(<%= rooms.collect {|r| r.house_keeping_status}.count {|i|i=='INSPECT'} %>);

    });
</script>

<style type="text/css">
    span[assigned_task_to_id] {
        padding: 2px 4px;
        background: #b0c0c9;
        border-radius: 5px !important;
        border: 1px solid #ffffff;
        position: relative;
    }

    span[assigned_task_to_id] a {
        position: absolute;
        top: -6px;
        color: #E31F1F;
    }

    .ltr span[assigned_task_to_id] a {
     right: 0;
    }

    .rtl span[assigned_task_to_id] a {
     left: 0;
    }


</style>

lib/dashboard/app/views/housekeeping/_housekeeping_print_content.html.erb
<link href="/assets/print_media_<%= I18n.locale.to_s %>.css" media="print" rel="stylesheet" type="text/css"/>
<div class="border_inner_box">
  <table border="0" cellpadding="0" cellspacing="0" style="width: 100%; margin-top: 5px;" class="tabular_fullwidth">
    <thead>
    <tr>
      <th style="width: 7%">
        <%= t('views.labels.room') %>
      </th>
      <th  style="width: 10%">
        <%= t('views.labels.room_type') %>
      </th>
      <th  style="width: 10%">
        <%= t('views.labels.housekeeping_status') %>
      </th>
      <th  style="width: 10%">
        <%= t('views.labels.front_desk_status') %>
      </th>
      <th  style="width: 28%">
        <%= t('views.labels.remarks') %>
      </th>
      <th  style="width: 20%">
        <%= t('views.labels.employee') + ' ' + t('views.labels.names') %>
      </th>
    </tr>
    </thead>
    <tbody>
    <%= render :partial => 'housekeeping/housekeeping_row', :locals => {:rooms =>@rooms, :status_data => @status_data} %>
    </tbody>

  </table>


</div>

lib/dashboard/app/views/housekeeping/_multple_room_assign_lb.html.erb
<a href="" class="lbOn" rel="multi_room_assign_lb"></a>
<div class="fi_light_box_row" id="multi_room_assign_lb" style="display: none;width: auto;left:20%;right:20%;z-index: 1001;position: absolute;">
  <div class="fi_head">
    <h1 id='task_lb_header'>
      <%= t('views.labels.assign_employee') %>
    </h1>
    <a class="fi_close multi_room_assign_lb_close" href="javascript:void(0)"></a>
  </div>
  <div class="qv_row charge_room" style="width: 96%">
    <div class="qv_row_full_content" id="multi_room_assign_lb_container" style="padding: 5px;">

    </div>
  </div>
</div>

lib/dashboard/app/views/housekeeping/_nav.html.erb
<ul class="jq-menu">

  <li>
    <%= link_to t('template.dashboard.front_desk'), front_desk_path, :class => "#{dashboard_nav_selected_class('front_desk')}" + ' first_child' %>
    <ul class="nav-sub-menu">
      <% if  hotel_agent? || has_any_role_with_hierarchy?(:check_in_manage_all) %>
          <li><%= link_to t('template.dashboard.walkin_checkin'), 'javascript:void(0)', :url => from_room_view_check_ins_path(:target_dom_id => 'fdr_checkin_form_content'), :class => 'for_tab_view', :rel => 'fdr_checkin_form', :title => t('views.labels.check_in') %></li>
      <% end %>
      <% if  hotel_agent? || has_any_role_with_hierarchy?(:reservation_manage_all) %>
          <li><%= link_to t('template.dashboard.reservation'), 'javascript:void(0)', :url => from_room_view_reservations_path(:target_dom_id => 'fdr_reservation_form_content'), :class => 'for_tab_view', :rel => 'fdr_reservation_form', :title => t('views.labels.reservation') %></li>
      <% end %>
      <% if  hotel_agent? || has_any_role_with_hierarchy?(:check_in_manage_all) %>
          <li><%= link_to t('views.labels.check_out'), "javascript:void(0)", :class => 'check_out ' %></li>
      <% end %>

      <% if hotel_agent? || has_any_role_with_hierarchy?(:check_in_add_edit_charge) %>
          <li><%= link_to t('template.dashboard.charge_room'), "javascript:void(0)", :class => 'chargeroom ' %>
      <% end %>
      <% if hotel_agent? || has_any_role_with_hierarchy?(:check_in_add_edit_payment) %>
          <li><%= link_to t('views.labels.manage_payment'), "javascript:void(0)", :class => 'manage_payment ' %>
      <% end %>
      <% if can_cash_closeout? %>
          <li><%= link_to t('template.dashboard.cash_close_out'), 'javascript:void(0)', :url => new_branch_panel_cash_closeout_path( :target_dom_id => 'fdr_cash_closeout_content'), :class => 'for_tab_view', :rel => 'fdr_cash_closeout', :title => t('views.labels.cash_closeout')  %></li>
      <% end %>
    </ul>
  </li>

  <li>
    <% if hotel_agent? || has_any_role_with_hierarchy?(:housekeeping_dashboard_view) %>
      <%= link_to t('template.dashboard.house_keeping'), housekeeping_path, :target => '_blank', :class => "#{dashboard_nav_selected_class('house_keeping')}" %>
    <% end %>
  </li>
  <!--<li>-->
  <!--<%#= link_to t('template.dashboard.cashier_desk'), :cashier_desk, :target => '_blank', :class => "dashboard_nav_selected_class('cashier_desk')" %>-->
  <!--</li>-->
  <li>
    <% if hotel_agent? || has_any_role_with_hierarchy?(:report_home) %>
      <%= link_to t('template.dashboard.hotel_admin_nav.reporting'), :reports_base, :target => '_blank', :class => "dashboard_nav_selected_class('reports_base')" %>
    <% end %>
  </li>

  <li>
    <% if hotel_agent? || has_any_role_with_hierarchy?(:room_service) %>
      <%= link_to t('views.labels.room_service'), :room_service, :target => '_blank', :class => "dashboard_nav_selected_class('room_service')" %>
    <% end %>
  </li>
  <li>
    <% if hotel_agent? %>
      <%= link_to t('template.dashboard.hotel_administration'), hotel_administration_path, :target => '_blank', :class => "dashboard_nav_selected_class('reports').to_s + ' last_child'" %>
    <% end %>
  </li>
</ul>

lib/dashboard/app/views/housekeeping/assign_employee.js.erb
$j('#flash_message_div').html("<%= escape_javascript(render :partial => 'parts/dashboard_flash_message') %>");
$j('#flash_message_div').slideDown().delay(10000);
DASHBOARD.TabView.refresh_tab('dashboard_home_tab');

lib/dashboard/app/views/housekeeping/home.html.erb
<% unless params.has_key?('action_type') %>
    <div class="group_type_tab tab_view">
      <ul id="v_tabs">
        <li>
          <%= link_to t('views.labels.dashboard'), housekeeping_path, :id => 'dashboard_home_tab', :title => t('views.labels.dashboard'), :class => 'h_tab_select', :remote => true %>
        </li>
        <%= render_refresh_tab(t('views.labels.dashboard'))%>
      </ul>
    </div>
<% end %>
<div class="quickview less_top" id="v_tab_content">
  <div id="housekeeping_dashboard_container" class="v_tab_content_item">
    <%= render :partial => 'housekeeping/home_content', :locals => {:assigned_users => @assigned_users, :rooms => @rooms, :status_data => @status_data, :room_types => @room_types, :selected_room_type => @selected_room_type} %>
  </div>
</div>