lib/dashboard/config/routes.rb
Moteel::Application.routes.draw do

  namespace :service do |serve|
    resources :hotels, :as => 'entity' do
      collection do
        get 'available_rooms'
        get 'managers'
        get 'users'

      end
    end
    resources :reservations do
      collection do
        get 'create'
        get 'show'
        get 'delete'
      end
    end
    resources :checkins, :controller => 'checkin' do
      member do
        post 'check_out'
        get 'add_service_charge'
        get 'add_service_payment'
      end
    end
  end
  resources :hotel_reviews, :as => 'entity_reviews'
  resources :hotel_modules, :as => 'entity_modules'

  resources :hotel_payment_types, :as => 'entity_payment_types' do
    member do
      put 'change_status'
    end
  end

  resources :hotel_discounts, :path => 'entity_discounts' do
    collection do
      post 'delete_multiple'
    end
  end
  resources :hotel_reviews, :as => 'entity_reviews'
  resources :hotels, :as => 'entity' do
    member do
      put 'change_status'
      put 'change_featured_status'
      delete 'delete_featured'
      get 'location_map'
      get 'amenities'
      get 'rooms'
      get 'policies'
      get 'description'
      get 'photos'
      get 'videos'
      get 'inquiry'
      get 'reviews'
      get 'contact'
      get 'invalidate_cache'
      get 'custom_action'
    end
    collection do
      get 'search'
      get 'country_changed'
      post 'send_feedback'
      post 'delete_image'
      get 'redirect_provider'
      get 'api_hotel_rooms'
      post 'delete_logo'
      get 'show_api'
      get 'assign_template'
      get 'assign_theme'
      post 'assign_theme'
      get 'render_google_map'
      get 'list'
      get 'featured_requests'
      get 'make_featured'
      post 'make_featured'
      get 'featured'
      post 'do_featured'
      post 'auto_complete_for_hotel'
    end
  end

  resources :rooms, :as => 'items' do
    collection do
      get 'category_changed'
      get 'info_for_reserve'
      get 'booking_local'
      get 'amenities'
      get 'available_particular_room'
      post 'delete_image'
      post 'add_service'
      post 'delete_multiple'
      post 'switch_branch'
      post 'auto_complete_results'
    end
    member do
      put 'change_status'
    end
  end
  resources :room_types, :as => 'item_types' do
    collection do
      get 'category_changed'
      get 'detail_info'
      get 'info_for_reserve'
      post 'delete_image'
      get 'amenities'
    end
    member do
      put 'change_status'
    end
  end
  namespace :user_panel do |user_panel|
    resources :hotels, :as => 'entity', :only => [:index] do
      collection do
        post 'make_featured'
        get 'check_in'
        get 'check_out'
        get 'clicked_bill'
      end
    end
    resources :hotel_assignments, :as => 'entity_assignments', :only => [:create]
    resources :recharge_requests, :only => [:index]
    resources :room_types, :as => 'item_types', :only => [:index]
    resources :rooms, :as => 'items', :only => [:index]
    resources :finances, :only => [:index] do
      collection do
        get 'view_balance'
        get 'billing_statement'
      end
    end

    resources :feedbacks, :only => [:index] do
      collection do
        get 'featured_request'
        get 'reply_feedback'
        get 'delete_feedback'
      end
    end
  end
  #resources :users
  get 'my/entity_reports' => 'users#moteel_reports_users', :as => 'moteel_reports_users'
  get 'assign_entity' => 'users#assign_hotel_users', :as => 'assign_hotel_users'

  get 'my/entity_list' => 'users#hotel_list_users', :as => 'hotel_list_users'
  get 'my/item_type_list' => 'users#room_type_list_users', :as => 'room_type_list_users'
  get 'my/item_list' => 'users#room_list_users', :as => 'room_list_users'

  get 'entity_visit_detail/:id' => 'users#hotel_visit_detail', :as => 'hotel_visit_detail'

  get 'dashboard' => 'dashboard#home', :as => 'dashboard_home'

  get 'housekeeping' => 'housekeeping#home', :as => 'housekeeping'
  get 'housekeeping_print' => 'housekeeping#home_print', :as => 'housekeeping_print'
  post 'update_housekeeping_status' => 'housekeeping#update_housekeeping_status'
  post 'assign_employee_housekeeping' => 'housekeeping#assign_employee'
  post 'remove_employee_housekeeping' => 'housekeeping#remove_employee'

  get 'room_service' => 'room_service#home', :as => 'room_service'
  post 'assign_employee_room_service' => 'room_service#assign_employee'
  post 'update_room_service_status' => 'room_service#update_status'

  get 'reports_base' => 'reports_base#home', :as => 'reports_base'
  get 'all_branch_reports' => 'all_branch_reports#home', :as => 'all_branch_reports'
  get 'room_occupancy_report' => 'reports_base#room_occupancy_report', :as => 'room_occupancy_report'
  get 'sales_by_services_report' => 'reports_base#sales_by_services_report', :as => 'sales_by_services_report'

  get 'cashier_desk' => 'cashier_desk#home'
  #For Report
  get 'inventory_transaction_list_report' => 'housekeeping/housekeeping_reports#inventory_transaction_list', :as => 'inventory_transaction_list_report'
  post 'inventory_transaction_list_report' => 'housekeeping/housekeeping_reports#inventory_transaction_list', :as => 'inventory_transaction_list_report'
  get 'fixed_asset_transactions_report' => 'housekeeping/housekeeping_reports#fixed_asset_allocation_history', :as => 'fixed_asset_transactions_report'
  post 'email_fixed_asset_allocation_pdf' => 'housekeeping/housekeeping_reports#email_fixed_asset_allocation_pdf', :as => 'email_fixed_asset_allocation_pdf'
  get 'service_wise_revenue_report' => 'housekeeping/housekeeping_reports#service_wise_revenue', :as => 'service_wise_revenue_report'
  post 'email_service_wise_revenue_pdf' => 'housekeeping/housekeeping_reports#email_service_wise_revenue_pdf', :as => 'email_service_wise_revenue_pdf'
  get 'payment_type_wise_transactions_report' => 'housekeeping/housekeeping_reports#payment_type_wise_transactions', :as => 'payment_type_wise_transactions_report'
  post 'payment_type_wise_transactions_report' => 'housekeeping/housekeeping_reports#payment_type_wise_transactions', :as => 'payment_type_wise_transactions_report'
  get 'deposit_listing_report' => 'housekeeping/housekeeping_reports#deposit_listing', :as => 'deposit_listing_report'
  post 'email_deposit_listing_pdf' => 'housekeeping/housekeeping_reports#email_deposit_listing_pdf', :as => 'email_deposit_listing_pdf'
  get 'financial_statement_report' => 'housekeeping/housekeeping_reports#financial_statement', :as => 'financial_statement_report'
  post 'financial_statement_report' => 'housekeeping/housekeeping_reports#financial_statement', :as => 'financial_statement_report'
  get 'billing_information_report' => 'housekeeping/housekeeping_reports#billing_information', :as => 'billing_information_report'
  post 'email_billing_information_pdf' => 'housekeeping/housekeeping_reports#email_billing_information_pdf', :as => 'email_billing_information_pdf'
  get 'cashier_statement_report' => 'housekeeping/housekeeping_reports#cashier_statement', :as => 'cashier_statement_report'
  post 'email_cashier_statement_pdf' => 'housekeeping/housekeeping_reports#email_cashier_statement_pdf', :as => 'email_cashier_statement_pdf'
  get 'revenue_by_counter_report' => 'housekeeping/housekeeping_reports#revenue_by_counter', :as => 'revenue_by_counter_report'
  post 'email_revenue_by_counter_pdf' => 'housekeeping/housekeeping_reports#email_revenue_by_counter_pdf', :as => 'email_revenue_by_counter_pdf'

  #End Report
  namespace :reporting_service do |service|
    resources :items do
      member do
        post 'create'
        get 'new'
      end
    end
  end
  get 'front_desk' => 'reporting_service/items#availability_list', :as => 'front_desk'
  get 'stay_view' => 'reporting_service/items#stay_view', :as => 'stay_view'
  get 'quick_view' => 'reporting_service/items#quick_view', :as => 'quick_view'
  get 'quick_view_future_inventory' => 'reporting_service/items#quick_view_future_inventory', :as => 'quick_view_future_inventory'
  get 'quick_view_future_inventory_more' => 'reporting_service/items#quick_view_future_inventory_more', :as => 'quick_view_future_inventory_more'
  #reporting
  get 'report_checkin' => 'reporting_service/reports#report_checkin', :as => 'report_checkin'
  get 'report_available' => 'reporting_service/reports#report_available', :as => 'report_available'
  get 'report_maintenance' => 'reporting_service/reports#report_maintenance', :as => 'report_maintenance'
  get 'report_pending_checkout' => 'reporting_service/reports#report_pending_checkout', :as => 'report_pending_checkout'

end

lib/dashboard/app/controllers/reporting_service/items_controller.rb
require 'mongo_sync_after_shard_sync'

class ReportingService::ItemsController < FrontDeskController
  include Moteel::MongoSyncAfterShardSync
  filter_access_to [:availability_list, :quick_view, :stay_view]

  before_filter :load_entities_for_front_desk, :only => [:availability_list, :quick_view, :stay_view]
  before_filter :mongo_sync_after_shard_sync, :only => [:availability_list, :quick_view, :stay_view]

  def index

  end

  def new
    @item = ReportItem.new
  end

  def create
    @item = ReportItem.new(params[:report_item])

    if @item.save
      flash[:notice] = @item.item_type_name
      redirect_to dashboard_home_path
    else
      flash[:error] = Common.validation_errors(@item.errors)
      render :new
    end
  end

  def availability_list
    reporting_date = params[:filter_start_date] || Time.zone.today
    @selected_menu = 'front_desk'
    @todays_activity_count = ReportEntityDailyActivity.where(:date => reporting_date, :entity_id => current_reporting_branch_id).first[:todays_activity_count] rescue {}
    @todays_activity_count ||= {}
    @filter_start_date = params[:filter_start_date].present? ? Time.zone.parse(params[:filter_start_date]) : Time.zone.today
    @filter_end_date = params[:filter_end_date].present? ? Time.zone.parse(params[:filter_end_date]) : Time.zone.today

    @items = ReportItemDailyActivity.generate_availability(current_reporting_branch_id, params[:item_type_id], @filter_start_date, @filter_end_date)
    @item_types = RoomType.where('room_types.hotel_id' => current_reporting_branch_id).includes(:translations)
    @item_with_task_count = {}
    @item_with_task_count = ReportTask.tasks_by_room_within_dates(current_reporting_branch_id, current_user.id, @filter_start_date, @filter_end_date)

    @items = fill_in_additional_data_for_template @items

    @custom_markers = Marker.by_entity(current_reporting_branch_id).includes(:translations)
    @compulsory_markers = Marker.compulsory.includes(:translations)
    @view_options_selected_tab = 'front_desk'
    respond_to do |format|
      format.html
      format.js
    end
  end


  def stay_view
    @view_options_selected_tab = 'stay_view'
    @item_types = RoomType.all(:include => :translations,
                               :conditions =>
                                   {'room_types.hotel_id' => current_reporting_branch_id})
    find_options, filter_options = prepare_finder_options
    unless current_reporting_branch_id.present?
      @no_data = true
      return false
    end
    @stay_view_data, @date_range, @grid_width = ReportItemDailyActivity.daily_activities_hash(
        params[:stay_view_filter_date], params[:days_count].to_i, find_options, {})
    @custom_markers = Marker.by_entity(current_reporting_branch_id)
    @compulsory_markers = Marker.compulsory
    respond_to do |format|
      format.html
      format.js
    end
  end

  def quick_view
    @view_options_selected_tab = 'quick_view'
    unless current_reporting_branch_id.present?
      @no_data = true
      return false
    end
    data = ReportEntityDailyActivity.where(:date => Time.zone.today, :entity_id => current_reporting_branch_id).first
    if data.nil?
      ReportEntityDailyActivity.update_daily_activities(current_reporting_branch_id, Time.zone.today)
      data = ReportEntityDailyActivity.where(:date => Time.zone.today, :entity_id => current_reporting_branch_id).first
    end

    @quick_view_data = data
    @data_after_today = ReportEntityDailyActivity.range_activity(current_reporting_branch_id, 12)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def quick_view_future_inventory
    if params[:check_in].present?
      start_date = Time.zone.parse(params[:check_in]).to_date
    else
      start_date = Time.zone.today
    end

    @data_after_today = ReportEntityDailyActivity.range_activity(current_reporting_branch_id, 3)

    respond_to do |format|
      format.js
    end
  end

  def quick_view_future_inventory_more
    if params[:start_date].present?
      start_date = Time.zone.parse(params[:start_date]).to_date
    else
      start_date = Time.zone.now.to_date
    end

    @data_after_today = ReportEntityDailyActivity.range_activity(current_reporting_branch_id, 12)

    respond_to do |format|
      format.js
    end
  end

  protected


  def prepare_finder_options
    #populate the find_option hash
    find_options = {}
    find_options[:entity_id] = current_reporting_branch_id.to_i if current_reporting_branch_id.present?
    find_options[:item_type_id] = params[:item_type_id].to_i if params[:item_type_id].present?

    #populate the find_option hash
    filter_options = {}

    filter_options[:entity_id] = current_reporting_branch_id.to_i if current_reporting_branch_id.present?
    filter_options[:item_type_id] = params[:item_type_id].to_i if params[:item_type_id].present?

    [find_options, filter_options]
  end

  def load_entities_for_front_desk
    @entities = Hotel.where('hotels.id' => manageable_hotel_ids).includes(:translations)
  end

  def fill_in_additional_data_for_template(items)
    items.each do |item|
      item[:multi_select_room] = item[:status] == Constants::ITEM_VIEW_AVAILABLE_STATUS
      item[:task_count] = @item_with_task_count[item[:item_id].to_s]
    end
  end
end

lib/dashboard/app/controllers/reporting_service/reports_controller.rb
class ReportingService::ReportsController < ApplicationController

  def check_in
    unless params[:current_reporting_branch_id].present?
      @current_total = ''
      @change_total = ''
      @change = ''
      return false
    end
    entity_id = current_reporting_branch_id
    days_count = params[:days_count].present? ? params[:days_count].to_i : 0

    @current_total, @change_total, @change = DashboardReport.get_check_in_report_data(entity_id, days_count)

    respond_to do |format|
      format.js
    end
  end

  def available
    unless params[:current_reporting_branch_id].present?
      @current_total = ''
      @change_total = ''
      @change = ''
      return false
    end
    entity_id = current_reporting_branch_id
    days_count = params[:days_count].present? ? params[:days_count].to_i : 0

    @current_total, @change_total, @change = DashboardReport.get_available_report_data(entity_id, days_count)

    respond_to do |format|
      format.js
    end
  end

  def maintenance
    unless params[:current_reporting_branch_id].present?
      @current_total = ''
      @change_total = ''
      @change = ''
      return false
    end
    entity_id = current_reporting_branch_id
    days_count = params[:days_count].present? ? params[:days_count].to_i : 0

    @current_total, @change_total, @change = DashboardReport.get_maintenance_report_data(entity_id, days_count)

    respond_to do |format|
      format.js
    end
  end

  def pending_checkout
    unless params[:current_reporting_branch_id].present?
      @current_total = ''
      @change_total = ''
      @change = ''
      return false
    end
    entity_id = current_reporting_branch_id
    days_count = params[:days_count].present? ? params[:days_count].to_i : 0

    @current_total, @change_total, @change = DashboardReport.get_pending_checkout_report_data(entity_id, days_count)

    respond_to do |format|
      format.js
    end
  end
end

lib/dashboard/app/helpers/reporting_service/items_helper.rb
module ReportingService::ItemsHelper
  def view_options_selected_tab(expected, classes = '')
    @view_options_selected_tab.to_s == expected ? 'h_tab_select '+ classes : classes
  end

  def merged_params_for_vew_options(p_hash = {})
    params.delete_if { |key, _| ['controller', 'action'].include? key }.merge(p_hash)
  end

  def merged_params_for_stay_view_date(type='next')
    days_count = params[:days_count].present? ? params[:days_count].to_i : 7
    filter_date = params[:stay_view_filter_date].present? ? params[:stay_view_filter_date].to_s : Time.zone.today.to_s
    filter_date = Time.zone.parse(filter_date)
    filter_date = type == 'next' ? (filter_date + days_count).to_s : (filter_date - days_count).to_s

    params.delete_if { |key, _| ['controller', 'action'].include? key }.merge(:stay_view_filter_date => filter_date)
  end
end

lib/dashboard/app/views/reporting_service/reports/_available.html.erb
<%= form_tag report_available_path, :method => 'get', :name => 'filter-from', :class => 'submit_on_load show_inner_loading', 'data-remote' => true do %>
  <div class="boxinfo">
    <h1><%= t('template.dashboard.reporting_service_report.room_available') %></h1>

    <div class="info">
      <%= select_tag('days_count', options_for_select(translate_days_count_options(Constants::DAYS_COUNT_OPTIONS_LESS), params[:days_count].to_i), :class => 'select_ajax_submit') %>
      <label><%= @current_total %></label>
    </div>
  </div>
  <%= hidden_field_tag 'current_reporting_branch_id', current_reporting_branch_id , :id => '', :class => 'current_reporting_branch_id' %>
  <div class="changed">
    <div class="stat <%= @change %>"></div>
    <div class="amount"><%= @change_total %></div>
  </div>
<% end %>

lib/dashboard/app/views/reporting_service/reports/_check_in.html.erb
<%= form_tag report_checkin_path, :method => 'get', :name => 'filter-from', :class => 'submit_on_load show_inner_loading', 'data-remote' => true do %>
  <div class="boxinfo">
    <h1><%= t('template.dashboard.reporting_service_report.checkin') %></h1>

    <div class="info">
      <%= select_tag('days_count', options_for_select(translate_days_count_options(Constants::DAYS_COUNT_OPTIONS), params[:days_count].to_i), :class => 'select_ajax_submit') %>
      <label><%= @current_total %></label>
    </div>
  </div>
  <%= hidden_field_tag 'current_reporting_branch_id', current_reporting_branch_id , :id => '', :class => 'current_reporting_branch_id' %>
  <div class="changed">
    <div class="stat <%= @change %>"></div>
    <div class="amount"><%= @change_total %></div>
  </div>
<% end %>

lib/dashboard/app/views/reporting_service/reports/_maintenance.html.erb
<%= form_tag report_maintenance_path, :method => 'get', :name => 'filter-from', :class => 'submit_on_load show_inner_loading', 'data-remote' => true do %>
  <div class="boxinfo">
    <h1><%= t('template.dashboard.reporting_service_report.room_in_maintenance') %></h1>

    <div class="info">
      <%= select_tag('days_count', options_for_select(translate_days_count_options(Constants::DAYS_COUNT_OPTIONS_LESS), params[:days_count].to_i), :class => 'select_ajax_submit') %>
      <label><%= @current_total %></label>
    </div>
  </div>
  <%= hidden_field_tag 'current_reporting_branch_id', current_reporting_branch_id , :id => '', :class => 'current_reporting_branch_id' %>
  <div class="changed">
    <div class="stat <%= @change %>"></div>
    <div class="amount"><%= @change_total %></div>
  </div>
<% end %>

lib/dashboard/app/views/reporting_service/reports/_pending_checkout.html.erb
<%= form_tag report_pending_checkout_path, :method => 'get', :name => 'filter-from', :class => 'submit_on_load show_inner_loading', 'data-remote' => true do %>
  <div class="boxinfo">
    <h1><%= t('template.dashboard.reporting_service_report.stay_over') %></h1>

    <div class="info">
      <%= select_tag('days_count', options_for_select(translate_days_count_options(Constants::DAYS_COUNT_OPTIONS_LESS), params[:days_count].to_i), :class => 'select_ajax_submit') %>
      <label><%= @current_total %></label>
    </div>
  </div>
  <%= hidden_field_tag 'current_reporting_branch_id', current_reporting_branch_id , :id => '', :class => 'current_reporting_branch_id' %>
  <div class="changed">
    <div class="stat <%= @change %>"></div>
    <div class="amount"><%= @change_total %></div>
  </div>
<% end %>

lib/dashboard/app/views/reporting_service/reports/_sales.html.erb
<div class="boxinfo">
  <h1><%= t('template.dashboard.reporting_service_report.total_sales') %></h1>

  <div class="info">
    <select>
      <option>Today</option>
    </select>
    <label>10000</label>
    <span>SAR</span>
  </div>
</div>
<div class="changed">
  <div class="stat up"></div>
  <div class="amount">12,000</div>
</div>

lib/dashboard/app/views/reporting_service/reports/available.js.erb
$j('#report_available').html('<%=escape_javascript(render :partial => 'available')%>');

lib/dashboard/app/views/reporting_service/reports/check_in.js.erb
$j('#report_check_in_list').html('<%=escape_javascript(render :partial => 'check_in')%>');

lib/dashboard/app/views/reporting_service/reports/maintenance.js.erb
$j('#report_maintenance').html('<%=escape_javascript(render :partial => 'maintenance')%>');

lib/dashboard/app/views/reporting_service/reports/pending_checkout.js.erb
$j('#report_pending_checkout').html('<%=escape_javascript(render :partial => 'pending_checkout')%>');